<a href="https://colab.research.google.com/github/TTReza/Pytorch_Knowledge/blob/master/tensors_torch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.3
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.6.0
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bi

In [2]:
import torch
import numpy as np

**List**

In [4]:
my_list = [1,2,3,4,5]
my_list1 = [[1,2,3], [4,5,6]]
my_list1

[[1, 2, 3], [4, 5, 6]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.28101421, 0.14653092, 0.05776909, 0.28112767],
       [0.86563007, 0.15648372, 0.36284589, 0.24225879],
       [0.68738738, 0.36771568, 0.07992451, 0.40240712]])

In [6]:
np1.dtype

dtype('float64')

**Tensor**

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.0009e+00, -2.8757e+00, -1.3927e+00, -2.0808e-01],
        [ 6.7811e-02,  1.6202e-03, -1.6585e+00, -3.0224e-03],
        [-2.4818e+00, -1.1059e+00,  1.1463e+00,  1.3952e+00]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2810, 0.1465, 0.0578, 0.2811],
        [0.8656, 0.1565, 0.3628, 0.2423],
        [0.6874, 0.3677, 0.0799, 0.4024]], dtype=torch.float64)

**Tensor Operations**

In [10]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#reshaping and view

my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
#view
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
#with reshape and view they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch5[1] = 343
my_torch5

tensor([  0, 343,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
my_torch6

tensor([[  0, 343,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [20]:
#slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch7[7]

tensor(7)

In [22]:
my_torch8 = my_torch7.reshape(5,2)

In [23]:
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [25]:
my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

**Math Operations**

In [26]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [27]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [28]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [29]:
#subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [30]:
#sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [32]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [33]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [34]:
#division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [35]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [36]:
#remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [38]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [39]:
# exponents

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [40]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [41]:
#antoher way to call functions
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [43]:
#reassignment

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [44]:
tensor_a = tensor_a + tensor_b

In [45]:
tensor_a

tensor([ 6,  8, 10, 12])